packages:
  - 'apps/trading-terminal'
  - 'apps/compliance-dashboard'
  - 'apps/custody-portal'
  - 'apps/admin-panel'
  - 'packages/shared-ui'
  - 'packages/shared-hooks'
  - 'packages/api-client'
  - 'packages/config'

catalogs:
  react:
    react: ^18.2.0
    react-dom: ^18.2.0
    react-router-dom: ^6.20.0

  vue:
    vue: ^3.3.0
    vue-router: ^4.2.0

  angular:
    '@angular/core': ^17.0.0
    '@angular/common': ^17.0.0
    '@angular/platform-browser': ^17.0.0
    '@angular/router': ^17.0.0

  next:
    next: ^14.0.0
    react: ^18.2.0
    react-dom: ^18.2.0

  shared:
    typescript: ^5.3.0
    '@typescript-eslint/eslint-plugin': ^6.13.0
    '@typescript-eslint/parser': ^6.13.0
    eslint: ^8.55.0
    prettier: ^3.1.0
    tailwindcss: ^3.3.0
